version: '3.8'

services:
  kafka-broker:
    image: apache/kafka:3.7.0 # kafka_2.13-3.7.0
    container_name: kafka-broker
    restart: "always"
    ports:
      - 9092:9092
      - 9094:9094
      - 8161:8161 
    volumes:
      - ./server.properties:/etc/kafka/docker/server.properties
      - ./data:/tmp/kraft-combined-logs
    networks:
      - devops-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - 18080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    # volumes:
    #   - ./kafka-ui-config.yml:/etc/kafkaui/dynamic_config.yaml
    networks:
      - devops-network

networks:
  devops-network:
    external: true

# for hacking delete topic errors in Windows: not working
# volumes:
#   kafka:
#     external: true
